name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build Lambda Packages
        run: |
          docker build -t lambda-builder -f docker/Dockerfile .
          docker run --rm \
            -v ${{ github.workspace }}:/build \
            lambda-builder \
            bash /build/scripts/build_lambda.sh

      - name: Build Lambda Layer
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/build \
            lambda-builder \
            bash /build/scripts/build_layer.sh
          
      - name: Upload Layer to S3
        run: |
          aws s3 cp layer/layer.zip s3://e-commerce-de-project/layer.zip

      - name: Publish Lambda Layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name ecommerce-dependencies \
            --content S3Bucket=e-commerce-de-project,S3Key=layer.zip \
            --compatible-runtimes python3.11 \
            --query 'LayerVersionArn' \
            --output text)
          
          echo "LAYER_ARN=$LAYER_ARN" >> $GITHUB_ENV

      - name: Deploy RDS Lambda
        run: |
          aws lambda update-function-code \
            --function-name rds_to_bronze \
            --zip-file fileb://rds_to_bronze.zip

      - name: Wait for RDS Lambda update
        run: |
          while true; do
            STATUS=$(aws lambda get-function-configuration \
              --function-name rds_to_bronze \
              --query 'LastUpdateStatus' \
              --output text)
          
            STATE=$(aws lambda get-function \
              --function-name rds_to_bronze \
              --query 'Configuration.State' \
              --output text)
          
            echo "Status: $STATUS"
            echo "State : $STATE"
          
            if [ "$STATUS" = "Successful" ] && [ "$STATE" = "Active" ]; then
              break
            fi
          
            sleep 5
          done

      - name: Attach Layer to RDS Lambda
        run: |
          aws lambda update-function-configuration \
            --function-name rds_to_bronze \
            --layers ${{ env.LAYER_ARN }}

      - name: Deploy External Files Lambda
        run: |
          aws lambda update-function-code \
            --function-name external_files_to_bronze \
            --zip-file fileb://external_files_to_bronze.zip

      - name: Wait for External Files Lambda update
        run: |
          while true; do
            STATUS=$(aws lambda get-function-configuration \
              --function-name external_files_to_bronze \
              --query 'LastUpdateStatus' \
              --output text)
          
            STATE=$(aws lambda get-function \
              --function-name external_files_to_bronze \
              --query 'Configuration.State' \
              --output text)
          
            echo "Status: $STATUS"
            echo "State : $STATE"
          
            if [ "$STATUS" = "Successful" ] && [ "$STATE" = "Active" ]; then
              break
            fi
          
            sleep 5
          done

      - name: Attach Layer to External Files Lambda
        run: |
          aws lambda update-function-configuration \
            --function-name external_files_to_bronze \
            --layers ${{ env.LAYER_ARN }}